"""empty message

Revision ID: b0b223d90ec7
Revises: ce6f9c2fe6bf
Create Date: 2021-11-25 03:07:03.964433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b223d90ec7'
down_revision = 'ce6f9c2fe6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'medicament', ['id'])
    op.create_unique_constraint(None, 'purchase', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'purchase', type_='unique')
    op.drop_constraint(None, 'medicament', type_='unique')
    # ### end Alembic commands ###
