"""Added column status

Revision ID: ce6f9c2fe6bf
Revises: f1ad729ae857
Create Date: 2021-11-12 13:36:17.526129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6f9c2fe6bf'
down_revision = 'f1ad729ae857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'status')
    # ### end Alembic commands ###
